version: "3.8"
services:

    # PHP Service
    php:
        image: mrschnoock/e-facture-php
        environment:
            - APP_ENV=local
            - CONTAINER_ROLE=app
            - MYSQL_HOST=database
            - MYSQL_USERNAME=root
            - MYSQL_PASSWORD=admin
            - MYSQL_DB=e-facture
        working_dir: /var/www
        volumes:
            - .:/var/www
        ports:
            - 8000:8000
        depends_on:
            - database

    # Database Server
    database:
        image: mrschnoock/e-facture-database
        ports:
            -   3306:3306
        environment:
            - MYSQL_DATABASE=e-facture
            - MYSQL_USER=root
            - MYSQL_PASSWORD=admin
            - MYSQL_ROOT_PASSWORD=admin
        volumes:
            - db-data:/var/lib/mysql

    # Node Server
    node:
        image: mrschnoock/e-facture-node
        volumes:
            - .:/usr/src
            - ./node_modules:/usr/src/node_modules
        tty: true
        command: sh -c "npm run dev"
volumes:
    db-data: ~
